name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chmod Permission
        run: sudo chmod +x ./gradlew
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Check Dependency Updates
        run: ./gradlew androidDependencies
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Decode Keystore
        run: echo ${{ secrets.BASE64_KEYSTORE }} | base64 -d > keystore
      - name: Create Keystore Properties
        run: |
          echo "releaseKeyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" > android/keystore.properties
          echo "releaseKeyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> android/keystore.properties
          echo "releaseKeyStore=keystore" >> android/keystore.properties
          echo "releaseStorePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> android/keystore.properties
      - name: Build Binary
        run: ./gradlew assembleRelease
      - name: Send Slack Message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,ref # repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Change File Name
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Cokedex-${{ github.run_number }}.apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Fokedex-${{ github.run_number }}
          path: app/build/outputs/apk/release/*.apk
      - name: Slack Upload Artifacts
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'app/build/outputs/apk/release/Fokedex-${{ github.run_number }}.apk'